<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>andres</groupId>
        <artifactId>practicojava</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>
    <artifactId>practicojava-client</artifactId>
    <packaging>jar</packaging>
    <name>practicojava - client</name>
    <description>Capa de presentación: aplicación Java de consola (cliente remoto)</description>

    <properties>
        <version.wildfly.client>41.0.1.Final</version.wildfly.client>
    </properties>

    <dependencies>
        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>practicojava-ejb</artifactId>
            <type>ejb</type>
        </dependency>
        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>practicojava-data</artifactId>
            <type>ejb</type>
        </dependency>

        <dependency>
            <groupId>org.wildfly</groupId>
            <artifactId>wildfly-client-all</artifactId>
            <version>${version.wildfly.client}</version>
        </dependency>
    </dependencies>

    <build>
        <finalName>${project.artifactId}</finalName>
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <version>3.5.1</version>
                <configuration>
                    <mainClass>andres.practicojava.cliente.ConsolaTrabajadores</mainClass>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
